# This Action Pubhlishes to NPM Automatically.
on:
  push:
    branches: main

jobs:
  publish: # Name
    runs-on: ubuntu-latest
    environment: npm-deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Run CI Step
        run: npm ci
      - name: Run Testing
        run: npm test
      - name: Publish to NPM 
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          registry: https://registry.npmjs.org
          access: public